### ISSUE TITLE
Issue using dynamic build and requirement on GLIBC

### ISSUE THREAD

**Issue by klauern** [open-policy-agent/setup-opa#15]
Hello!

I don't have a way to share this, but we are trying to use this action on our self-hosted runners, and ran into an issue with `opa` requiring GLIBC:

```
Run opa test configuration_rules/ -v
  opa test configuration_rules/ -v
  shell: /bin/bash -e {0}
opa: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by opa)
opa: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by opa)
Error: Process completed with exit code 1.
```

I ended up switching this action out by `curl`'ing the static binary and adding it to the path, but it would be nice if this action did that as well.  Here's my substitution for the `setup-opa` task:

```
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.39.0/opa_linux_amd64_static
          chmod 755 opa
          mkdir -p ~/.local/bin
          mv opa ~/.local/bin/opa
          echo "$HOME/.local/bin" >> $GITHUB_PATH
```

**Comment by tim775** [comment]
Thanks for the report!  I think it would solve your problem if we added a new `static` input to select which binary you need, right?  

Something like:
```
 ...
  static:
    description: Install the statically linked version of the OPA binary.  Usefull when GLIBC is not installed on self-hosted runners.
    required: false
    default: false
```

(PS let me know if you want to [contribute the code](https://www.openpolicyagent.org/docs/latest/contributing/) too)
